### ISSUE TITLE
Domínios PyTalks

### ISSUE THREAD

**Issue by sergiomario** [pythonbrasil/PyTalks#1]
@rochacbruno o Stamatios Junior de Floripa comprou os domínios:
pytalks.com/br/
pytalks.org
pytalks.com

Nos próximos meses faremos um evento PyTalks+DjangoGirls.

O que acha de aproveitarmos esse repositório e criarmos uma página estática aqui, apontando os domínios do Junior para cá? Daí a gente anuncia todos os PyTalks que ocorrem no Brasil.

Valeu :)

**Comment by rochacbruno** [comment]
Apoiado! :+1:

**Comment by rochacbruno** [comment]
Esse repo foi feito para a PyBR 2011 em SP e nunca foi usado.. o sistema PyTalks existiu, mas ocorreram diversos problemas administrativos que fizeram com que ele moresse..

E eu fiz questão de deletar o código.. rs

**Comment by sergiomario** [comment]
Entendi. Vou organizar o pessoal para iniciarmos o desenvolvimento então.

Obrigado Bruno.

**Comment by ssjunior** [comment]
Boa.. @sergiomario nós já temos uma página com logo feito pelos nossos designers.. depois vou publicar para vc dar uma olhada.

**Comment by sergiomario** [comment]
Que ótimo @ssjunior pode publicar 0//

**Comment by rougeth** [comment]
Pessoal, como a revitalização do projeto não foi para frente, vou arquivar o repositório.
